const {
  createRoute,
  createHandler,
  login,
  refresh,
  logout,
  me,
  listUsers,
  getUser,
  listVendors,
  updateVendorStatus,
  getVendorProfile,
  updateVendorProfile,
  getVendorDashboardStats,
  listVendorProducts,
  createVendorProduct,
  updateVendorProduct,
  deleteVendorProduct,
  listCategories,
  getCategory,
  createCategory,
  updateCategory,
  deleteCategory,
  listAdmins,
  createAdmin,
  updateAdmin,
  deleteAdmin,
  getAdminDashboardStats,
  getAdminProductAnalytics,
  listReferrals,
  getReferral,
  validateReferral,
  createReferral,
  updateReferral,
  updateReferralStatusByCode,
  deleteReferral,
  getReferralStats,
  getAllSettings,
  getPublicSettings,
  updateSettings,
  getRssProxy,
  getLocations,
  getNigeriaCatalog,
  createLocation,
  updateLocation,
  deleteLocation,
  createProduct,
  listProducts,
  getProduct,
  updateProduct,
  deleteProduct,
  approveProduct,
  rejectProduct,
  trackView,
  getProductAnalytics,
  verifyPaymentStatus,
  listPayments,
  uploadMedia,
  uploadMediaFile,
  listMedia,
  deleteMedia,
  getUserThreads,
  getUserThreadByVendor,
  sendUserMessage,
  editUserMessage,
  deleteUserMessage,
  markUserThreadRead,
  getVendorThreads,
  getVendorThreadByMarketUser,
  sendVendorMessage,
  editVendorMessage,
  deleteVendorMessage,
  markVendorThreadRead,
  listAllStores,
  searchStores,
  getStoreInfo,
  getStoreProducts,
  getStoreProduct,
  getPublicProductById,
  getFeaturedProducts,
  getNewArrivals,
  searchAllProducts,
  marketplaceOverview,
} = require("@migration/shared");

const routes = [
  createRoute("POST", "/api/v1/auth/login", login),
  createRoute("POST", "/api/v1/auth/refresh", refresh),
  createRoute("POST", "/api/v1/auth/logout", logout),
  createRoute("GET", "/api/v1/auth/me", me),

  createRoute("GET", "/api/v1/users", listUsers),
  createRoute("GET", "/api/v1/users/:id", getUser),

  createRoute("GET", "/api/v1/vendors", listVendors),
  createRoute("PATCH", "/api/v1/vendors/:id/status", updateVendorStatus),
  createRoute("GET", "/api/v1/vendors/me", getVendorProfile),
  createRoute("PATCH", "/api/v1/vendors/me", updateVendorProfile),
  createRoute("GET", "/api/v1/vendors/me/stats", getVendorDashboardStats),
  createRoute("GET", "/api/v1/vendors/me/products", listVendorProducts),
  createRoute("POST", "/api/v1/vendors/products", createVendorProduct),
  createRoute("PUT", "/api/v1/vendors/me/products/:id", updateVendorProduct),
  createRoute("PATCH", "/api/v1/vendors/me/products/:id", updateVendorProduct),
  createRoute("DELETE", "/api/v1/vendors/me/products/:id", deleteVendorProduct),

  createRoute("GET", "/api/v1/categories", listCategories),
  createRoute("GET", "/api/v1/categories/:id", getCategory),
  createRoute("POST", "/api/v1/categories", createCategory),
  createRoute("PATCH", "/api/v1/categories/:id", updateCategory),
  createRoute("PUT", "/api/v1/categories/:id", updateCategory),
  createRoute("DELETE", "/api/v1/categories/:id", deleteCategory),

  createRoute("GET", "/api/v1/admins/list", listAdmins),
  createRoute("POST", "/api/v1/admins", createAdmin),
  createRoute("PATCH", "/api/v1/admins/:id", updateAdmin),
  createRoute("DELETE", "/api/v1/admins/:id", deleteAdmin),
  createRoute("GET", "/api/v1/admins/stats", getAdminDashboardStats),
  createRoute("GET", "/api/v1/admins/products/analytics", getAdminProductAnalytics),

  createRoute("GET", "/api/v1/referrals/validate/:code", validateReferral),
  createRoute("POST", "/api/v1/referrals/generate", createReferral),
  createRoute("GET", "/api/v1/referrals/:id/stats", getReferralStats),
  createRoute("PATCH", "/api/v1/referrals/:code/status", updateReferralStatusByCode),
  createRoute("GET", "/api/v1/referrals", listReferrals),
  createRoute("GET", "/api/v1/referrals/:id", getReferral),
  createRoute("PATCH", "/api/v1/referrals/:id", updateReferral),
  createRoute("DELETE", "/api/v1/referrals/:id", deleteReferral),

  createRoute("GET", "/api/v1/settings/public", getPublicSettings),
  createRoute("GET", "/api/v1/settings/rss-proxy", getRssProxy),
  createRoute("GET", "/api/v1/settings", getAllSettings),
  createRoute("PATCH", "/api/v1/settings", updateSettings),

  createRoute("GET", "/api/v1/locations/catalog/nigeria", getNigeriaCatalog),
  createRoute("GET", "/api/v1/locations", getLocations),
  createRoute("POST", "/api/v1/locations", createLocation),
  createRoute("PATCH", "/api/v1/locations/:id", updateLocation),
  createRoute("DELETE", "/api/v1/locations/:id", deleteLocation),

  createRoute("POST", "/api/v1/products", createProduct),
  createRoute("GET", "/api/v1/products", listProducts),
  createRoute("GET", "/api/v1/products/analytics/mine", getProductAnalytics),
  createRoute("GET", "/api/v1/products/:id", getProduct),
  createRoute("PATCH", "/api/v1/products/:id", updateProduct),
  createRoute("DELETE", "/api/v1/products/:id", deleteProduct),
  createRoute("PATCH", "/api/v1/products/:id/approve", approveProduct),
  createRoute("PATCH", "/api/v1/products/:id/reject", rejectProduct),
  createRoute("POST", "/api/v1/products/:id/view", trackView),

  createRoute("GET", "/api/v1/payments", listPayments),
  createRoute("GET", "/api/v1/payments/verify/:reference", verifyPaymentStatus),

  createRoute("POST", "/api/v1/media/upload", uploadMedia),
  createRoute("POST", "/api/v1/media/uploadfile", uploadMediaFile),
  createRoute("GET", "/api/v1/media", listMedia),
  createRoute("DELETE", "/api/v1/media/:id", deleteMedia),

  createRoute("GET", "/api/v1/chat/user/threads", getUserThreads),
  createRoute("GET", "/api/v1/chat/user/thread/:vendorMongoId", getUserThreadByVendor),
  createRoute("POST", "/api/v1/chat/user/thread/:vendorMongoId/messages", sendUserMessage),
  createRoute("PATCH", "/api/v1/chat/user/thread/:vendorMongoId/messages/:messageId", editUserMessage),
  createRoute("DELETE", "/api/v1/chat/user/thread/:vendorMongoId/messages/:messageId", deleteUserMessage),
  createRoute("POST", "/api/v1/chat/user/thread/:vendorMongoId/read", markUserThreadRead),

  createRoute("GET", "/api/v1/chat/vendor/threads", getVendorThreads),
  createRoute("GET", "/api/v1/chat/vendor/thread/:marketUserId", getVendorThreadByMarketUser),
  createRoute("POST", "/api/v1/chat/vendor/thread/:marketUserId/messages", sendVendorMessage),
  createRoute("PATCH", "/api/v1/chat/vendor/thread/:marketUserId/messages/:messageId", editVendorMessage),
  createRoute("DELETE", "/api/v1/chat/vendor/thread/:marketUserId/messages/:messageId", deleteVendorMessage),
  createRoute("POST", "/api/v1/chat/vendor/thread/:marketUserId/read", markVendorThreadRead),

  createRoute("GET", "/api/v1/storefront/stores", listAllStores),
  createRoute("GET", "/api/v1/storefront/stores/search", searchStores),
  createRoute("GET", "/api/v1/storefront/products/featured", getFeaturedProducts),
  createRoute("GET", "/api/v1/storefront/products/new", getNewArrivals),
  createRoute("GET", "/api/v1/storefront/products/search", searchAllProducts),
  createRoute("GET", "/api/v1/storefront/products/:id", getPublicProductById),
  createRoute("GET", "/api/v1/storefront/store/info", getStoreInfo),
  createRoute("GET", "/api/v1/storefront/store/products", getStoreProducts),
  createRoute("GET", "/api/v1/storefront/store/products/:id", getStoreProduct),

  createRoute("GET", "/api/v1/analytics/overview", marketplaceOverview),
];

module.exports = async (context) => createHandler(routes)(context);
